language: c
env:
  - ZENOH_DEBUG=0
script:
  - make gcov
  - sudo make install
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat ./build/Testing/Temporary/LastTest.log