#ifndef ZENOH_C_NET_CONFIG_H
#define ZENOH_C_NET_CONFIG_H

#define ZENOH_NET_READ_BUF_LEN 65563
#define ZENOH_NET_WRITE_BUF_LEN 65563
#define ZENOH_NET_PID_LENGTH 8
#define ZENOH_NET_PROTO_VERSION 0x01
#define ZENOH_NET_DEFAULT_LEASE 10000

#define ZENOH_NET_SCOUT_MCAST_ADDR "239.255.0.1"
#define ZENOH_NET_LOCAL_HOST "127.0.0.1"
#define ZENOH_NET_MAX_SCOUT_MSG_LEN 1024
#define ZENOH_NET_SCOUT_PORT 7447
#define ZENOH_NET_SCOUT_TRIES 3
#define ZENOH_NET_SCOUT_TIMEOUT 100000 

#define ZENOH_NET_TRANSPORT_TCP_IP 1
// #define ZENOH_NET_TRANSPORT_BLE 1

#endif /* ZENOH_C_NET_CONFIG_H */
