name: Build cross-platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build cross-platforms
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make all-cross
      run: make all-cross
    - name: Gather artifacts
      run: |
        mkdir -p artifacts/zenoh-c
        for dir in `ls build/crossbuilds`; do
          mkdir -p artifacts//zenoh-c/$dir/example/net
          cp build/crossbuilds/$dir/lib*.* artifacts/zenoh-c/$dir/
          cp build/crossbuilds/$dir/zn_* artifacts//zenoh-c/$dir/example/net
        done
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: zenoh-c-all-platforms
        # Directory containing files to upload
        path: artifacts/zenoh-c
